### ISSUE TITLE
Error in parsing configuration

### ISSUE THREAD

**Issue by kmaras77** [openNDS/mesh11sd#90] opened 2024-09-08 21:00 UTC
When service is started and running, it still writes to sylog:

```
daemon.info mesh11sd[11494]: No mesh interfaces detected yet.... Attempting auto configure
daemon.err mesh11sd[11494]: auto_config is disabled. Please configure a mesh interface or enable auto_config....

```
I have checked the code and there is a syntax error in the printf parameters, no coma.
Is {printf "%s " $1} an should be {printf "%s ", $1}

```
if [ "$enabled" = 1 ]; then
			#get list of mesh configs
			meshconfigs=$(uci show wireless 2> /dev/null | grep "mode='mesh'" | awk -F ".mode='mesh'" '{printf "%s " $1}')

			if [ -z "$meshconfigs" ]; then
				# no mesh configuration yet
				debugtype="info"
				syslogmessage="No mesh interfaces detected yet.... Attempting auto configure"
				write_to_syslog

				############# Autoconfig

				if [ "$auto_config" -eq 1 ]; then
					auto_config
				else
					debugtype="err"
					syslogmessage="auto_config is disabled. Please configure a mesh interface or enable auto_config...."
					write_to_syslog
					sleep $checkinterval
				fi

				########################
			fi

			# Is the list of meshconfigs still empty?
			if [ -z "$meshconfigs" ]; then
				meshconfigs=$(uci show wireless 2> /dev/null | grep "mode='mesh'" | awk -F ".mode='mesh'" '{printf "%s "  $1}')
			fi
```

**Comment by bluewavenet** [comment] 2024-09-09 07:22
@kmaras77 

>  in the printf parameters, no com[m]a.

Thank you, well spotted!

However, the syslog output is normal and expected:

> When service is started and running, it still writes to sylog:
> 
> ```
> daemon.info mesh11sd[11494]: No mesh interfaces detected yet.... Attempting auto configure
> daemon.err mesh11sd[11494]: auto_config is disabled. Please configure a mesh interface or enable auto_config....
> ```

The missing comma does not cause a problem:
```
root@meshnode-c525:/# meshconfigs=$(uci show wireless 2> /dev/null | grep "mode='mesh'" | awk -F ".mode='mesh'" '{printf "%s " $1}'); echo "!$meshconfigs!"
! wireless.m11s0 wireless.m11s1!

root@meshnode-c525:/# meshconfigs=$(uci show wireless 2> /dev/null | grep "mode='mesh'" | awk -F ".mode='mesh'" '{printf "%s ", $1}'); echo "!$meshconfigs!"
!wireless.m11s0 wireless.m11s1 !
root@meshnode-c525:/# 

```
As can be seen above, the missing comma causes a leading space to be added and the trailing space to be missing but this has no effect on the parsing.

Here is an example of the startup sequence on my test system, where I set auto_config to 0:

```
root@meshnode-c525:/# uci set mesh11sd.setup.auto_config='0'
root@meshnode-c525:/# 
root@meshnode-c525:/# uci commit mesh11sd
root@meshnode-c525:/# service mesh11sd start; logread -f
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option enabled [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option debuglevel [ 3 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option checkinterval [ 10 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option portal_detect [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option portal_channel [ default ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option channel_tracking_checkinterval [ 30 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option portal_detect_threshold [ 3 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_path_cost [ 10 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option interface_timeout [ 10 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option auto_config [ 0 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: auto_mesh_id hash [ 92d490daf46cfe534c56ddd669297e ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option auto_mesh_band [ 2g40 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option auto_mesh_key [ 78c8068012f8481fec118451e1041b3751801a24ab3e222643a0a6a4424b82a1 ]
Mon Sep  9 06:58:31 2024 daemon.warn mesh11sd[9095]: option auto_mesh_network is not configured, defaulting to [ lan ]. Is this what you intended?
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option auto_mesh_network [ lan ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option auto_mesh_network [ lan ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_basename [ m-11s- ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_gate_encryption [ 0 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_gate_key [  ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_gate_enable [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_leechmode_enable [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option ssid_suffix_enable [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option watchdog_nonvolatile_log [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.warn mesh11sd[9095]: ******WARNING******: Irrepairable flash wear will occur and storage space will be used up. Please disable watchdog nonvolatile logging as soon as possible.
Mon Sep  9 06:58:31 2024 daemon.warn mesh11sd[9095]: ******WARNING******: Irrepairable flash wear will occur and storage space will be used up by watchdog debug log at /mesh11sd_log/watchdog.log
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_path_stabilisation [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_mac_forced_forwarding [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option gateway_proxy_arp [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option reboot_on_error [ 1 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option stop_on_error [ 0 ]
Mon Sep  9 06:58:31 2024 daemon.notice mesh11sd[9095]: mesh11sd is in startup
Mon Sep  9 06:58:31 2024 daemon.debug mesh11sd[9095]: Kernel version: Major [ 6 ], Minor [ 6 ], Patch [ 45 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_fwding [ 0 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_retry_timeout [ 255 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_confirm_timeout [ 255 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_holding_timeout [ 255 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_rssi_threshold [ -65 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_gate_announcements [ 0 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_hwmp_rootmode [ 4 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_hwmp_rann_interval [ 5000 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_hwmp_root_interval [ 5000 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_hwmp_active_path_timeout [ 5000 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_hwmp_active_path_to_root_timeout [ 6000 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_max_peer_links [ 16 ]
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: option mesh_plink_timeout [ 10 ]
Mon Sep  9 06:58:31 2024 daemon.notice mesh11sd[9095]: mesh11sd v4.2.0beta has started: mesh management mode 1
Mon Sep  9 06:58:31 2024 daemon.info mesh11sd[9095]: No mesh interfaces detected yet.... Attempting auto configure
Mon Sep  9 06:58:31 2024 daemon.err mesh11sd[9095]: auto_config is disabled. Please configure a mesh interface or enable auto_config....
Mon Sep  9 06:58:41 2024 daemon.info mesh11sd[9095]: No mesh interfaces detected yet.... Attempting auto configure
Mon Sep  9 06:58:41 2024 daemon.err mesh11sd[9095]: auto_config is disabled. Please configure a mesh interface or enable auto_config....
Mon Sep  9 06:58:51 2024 daemon.info mesh11sd[9095]: No mesh interfaces detected yet.... Attempting auto configure
Mon Sep  9 06:58:51 2024 daemon.err mesh11sd[9095]: auto_config is disabled. Please configure a mesh interface or enable auto_config....

```
Are you seeing something different?

**_Regardless,  the "missing comma" should definitely be fixed._**

**Comment by bluewavenet** [comment] 2024-09-09 07:24
@kmaras77 
For completeness, here is the startup sequence with auto_config set to 1:
```
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option enabled [ 1 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option debuglevel [ 3 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option checkinterval [ 10 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option portal_detect [ 1 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option portal_channel [ default ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option channel_tracking_checkinterval [ 30 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option portal_detect_threshold [ 3 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option mesh_path_cost [ 10 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option interface_timeout [ 10 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option auto_config [ 1 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: auto_mesh_id hash [ 92d490daf46cfe534c56ddd669297e ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option auto_mesh_band [ 2g40 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option auto_mesh_key [ 78c8068012f8481fec118451e1041b3751801a24ab3e222643a0a6a4424b82a1 ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option auto_mesh_network [ lan ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option auto_mesh_network [ lan ]
Mon Sep  9 07:16:55 2024 daemon.info mesh11sd[11362]: option mesh_basename [ m-11s- ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_gate_encryption [ 0 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_gate_key [  ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_gate_enable [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_leechmode_enable [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option ssid_suffix_enable [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option watchdog_nonvolatile_log [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.warn mesh11sd[11362]: ******WARNING******: Irrepairable flash wear will occur and storage space will be used up. Please disable watchdog nonvolatile logging as soon as possible.
Mon Sep  9 07:16:56 2024 daemon.warn mesh11sd[11362]: ******WARNING******: Irrepairable flash wear will occur and storage space will be used up by watchdog debug log at /mesh11sd_log/watchdog.log
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_path_stabilisation [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option mesh_mac_forced_forwarding [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option gateway_proxy_arp [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option reboot_on_error [ 1 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: option stop_on_error [ 0 ]
Mon Sep  9 07:16:56 2024 daemon.notice mesh11sd[11362]: mesh11sd is in startup
Mon Sep  9 07:16:56 2024 daemon.debug mesh11sd[11362]: Kernel version: Major [ 6 ], Minor [ 6 ], Patch [ 45 ]
Mon Sep  9 07:16:56 2024 daemon.info mesh11sd[11362]: Initialising state for auto_config
...
...
```

**Comment by bluewavenet** [comment] 2024-09-09 07:56
@kmaras77 
Fixed in commit https://github.com/openNDS/mesh11sd/pull/91/commits/1846074500536a36c03639c86068187ae210906b

**Comment by kmaras77** [comment] 2024-09-09 08:16
Please check the commands further:

#mesh11sd status
awk: cmd. line:1: (FILENAME=- FNR=2) fatal: not enough arguments to satisfy format string
        `%s phy1-mesh0'
         ^ ran out for this one
{
  "setup":{
    "version":"4.1.1",
    "enabled":"1",
    "procd_status":"running",
    "portal_detect":"1",
    "portal_detect_threshold":"0",
    "portal_channel":"default",
    "channel_tracking_checkinterval":"30",
    "mesh_basename":"m-11s-",
    "auto_config":"0",
    "auto_mesh_network":"lan",
    "auto_mesh_band":"2g40",
    "auto_mesh_id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "mesh_gate_enable":"1",
    "mesh_leechmode_enable":"0",
    "mesh_gate_encryption":"0",
awk: cmd. line:1: (FILENAME=- FNR=2) fatal: not enough arguments to satisfy format string
        `%s phy1-mesh0'
         ^ ran out for this one
    "txpower":"",
    "mesh_path_cost":"10",
    "mesh_path_stabilisation":"1",
    "checkinterval":"10",
    "interface_timeout":"10",
    "ssid_suffix_enable":"1",
    "debuglevel":"2"
  },
  "interfaces":{
  }
}



# mesh11sd stations
awk: cmd. line:1: (FILENAME=- FNR=2) fatal: not enough arguments to satisfy format string
        `%s phy1-mesh0'
         ^ ran out for this one
===========================================================================
Mesh backhaul stations connected to this node:
===========================================================================

**Comment by bluewavenet** [comment] 2024-09-09 16:47
@kmaras77 
`awk: cmd. line:1: (FILENAME=- FNR=2) fatal: not enough arguments to satisfy format string`

It seems you are using an installed "full" version of awk. The Busybox version works ok as I demonstrated.

> After commit https://github.com/openNDS/mesh11sd/commit/1846074500536a36c03639c86068187ae210906b it looks OK.

Excellent ;-)

**Comment by kmaras77** [comment] 2024-09-09 19:23
There is another place with this missing comma.

line 3433
`uci show wireless | grep "ifname='$iface'" | awk -F "." '{printf "wireless.%s" $2}'`

**Comment by bluewavenet** [comment] 2024-09-09 20:16
@kmaras77 
See commit https://github.com/openNDS/mesh11sd/pull/92/commits/ca8f0cdbc8121b8ae0f67cfdea712d5f23d09eb0
Again, this issue is not seen if using Busybox awk.

**Comment by kmaras77** [comment] 2024-09-09 22:19
"Again, this issue is not seen if using Busybox awk."
You are right, but gawk is in the dependencies of the adblock package.

**Comment by bluewavenet** [comment] 2024-09-10 07:44
@kmaras77 
As far as I can see, the issue is now fixed. Re-open this issue if you find any more.

**Closed by bluewavenet** 2024-09-10 07:44 UTC
